-- MySQL Script generated by MySQL Workbench
-- Sun Nov 17 16:14:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_epis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_epis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_epis` DEFAULT CHARACTER SET utf8 ;
USE `db_epis` ;

-- -----------------------------------------------------
-- Table `db_epis`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_epis`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(255) NULL,
  `senha` VARCHAR(255) NULL,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_epis`.`colaboradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_epis`.`colaboradores` (
  `id_colaborador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `cpf` VARCHAR(255) NULL,
  `sexo` CHAR(2) NULL,
  `idade` INT NULL,
  PRIMARY KEY (`id_colaborador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_epis`.`equipamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_epis`.`equipamentos` (
  `id_equipamento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `descricao` LONGTEXT NULL,
  `qtd_equipamento` INT NULL,
  `imagem` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_equipamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_epis`.`emprestimos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_epis`.`emprestimos` (
  `id_emprestimo` INT NOT NULL,
  `data` DATETIME NULL DEFAULT NULL,
  `quantidade` INT(11) NULL DEFAULT NULL,
  `cancelado` CHAR(1) NULL DEFAULT NULL,
  `id_usuario` INT NOT NULL,
  `id_colaborador` INT NOT NULL,
  `id_epis` INT NOT NULL,
  PRIMARY KEY (`id_emprestimo`),
  INDEX `fk_emprestimos_usuarios_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_emprestimos_colaboradores1_idx` (`id_colaborador` ASC) VISIBLE,
  INDEX `fk_emprestimos_epis1_idx` (`id_epis` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimos_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_epis`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimos_colaboradores1`
    FOREIGN KEY (`id_colaborador`)
    REFERENCES `db_epis`.`colaboradores` (`id_colaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimos_epis1`
    FOREIGN KEY (`id_epis`)
    REFERENCES `db_epis`.`equipamentos` (`id_equipamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
